import { describe, it, expect, beforeEach } from 'vitest';
import {
  generateTotpSecret,
  generateTotpToken,
  verifyTotpToken,
} from '../src/totp';
import { authenticator } from 'otplib';

describe('TOTP helpers using otplib', () => {
  beforeEach(() => {
    // Reset otplib options before each test
    authenticator.options = {};
  });

  it('generates TOTP secret using otplib', () => {
    const secret = generateTotpSecret();
    
    expect(secret).toBeDefined();
    expect(typeof secret).toBe('string');
    expect(secret.length).toBeGreaterThan(0);
    expect(/^[A-Z2-7]+=*$/.test(secret)).toBe(true); // Base32 pattern
  });

  it('generates different secrets each time', () => {
    const secret1 = generateTotpSecret();
    const secret2 = generateTotpSecret();
    
    expect(secret1).not.toBe(secret2);
  });

  it('generates TOTP token with default parameters', () => {
    const secret = 'JBSWY3DPEHPK3PXP'; // Test secret
    const token = generateTotpToken(secret);
    
    expect(token).toBeDefined();
    expect(typeof token).toBe('string');
    expect(token).toHaveLength(6);
    expect(/^\d{6}$/.test(token)).toBe(true);
  });

  it('generates TOTP token with custom parameters', () => {
    const secret = 'JBSWY3DPEHPK3PXP';
    const token = generateTotpToken(secret, 60, 8);
    
    expect(token).toHaveLength(8);
    expect(/^\d{8}$/.test(token)).toBe(true);
  });

  it('generates consistent tokens for same time', () => {
    const secret = 'JBSWY3DPEHPK3PXP';
    
    // Mock time to ensure consistency
    const mockTime = Date.now();
    const originalDateNow = Date.now;
    Date.now = () => mockTime;
    
    try {
      const token1 = generateTotpToken(secret);
      const token2 = generateTotpToken(secret);
      
      expect(token1).toBe(token2);
    } finally {
      Date.now = originalDateNow;
    }
  });

  it('verifies correct TOTP token', () => {
    const secret = 'JBSWY3DPEHPK3PXP';
    const token = generateTotpToken(secret);
    
    expect(verifyTotpToken(secret, token)).toBe(true);
  });

  it('rejects incorrect TOTP token', () => {
    const secret = 'JBSWY3DPEHPK3PXP';
    const wrongToken = '123456';
    
    expect(verifyTotpToken(secret, wrongToken)).toBe(false);
  });

  it('verifies TOTP token within time window', () => {
    const secret = 'JBSWY3DPEHPK3PXP';
    const token = generateTotpToken(secret);
    
    // Should verify with default window of 1 (±1 time step)
    expect(verifyTotpToken(secret, token, 30, 1)).toBe(true);
  });

  it('handles edge cases gracefully', () => {
    const secret = 'JBSWY3DPEHPK3PXP';
    
    // Should not throw errors for edge cases
    expect(() => generateTotpToken(secret)).not.toThrow();
    expect(() => verifyTotpToken(secret, '123456')).not.toThrow();
  });

  it('works with otplib directly for compatibility', () => {
    const secret = generateTotpSecret();
    
    // Generate token using our wrapper
    const ourToken = generateTotpToken(secret);
    
    // Generate token using otplib directly
    const otplibToken = authenticator.generate(secret);
    
    // They should be the same (within time tolerance)
    expect(ourToken).toMatch(/^\d{6}$/);
    expect(otplibToken).toMatch(/^\d{6}$/);
  });

  it('verifies tokens generated by otplib directly', () => {
    const secret = generateTotpSecret();
    const otplibToken = authenticator.generate(secret);
    
    // Our verifier should work with otplib-generated tokens
    expect(verifyTotpToken(secret, otplibToken)).toBe(true);
  });
});
