const StyleDictionary = require('style-dictionary');

// Custom transform for OKLCH color format
StyleDictionary.registerTransform({
  name: 'color/oklch',
  type: 'value',
  transitive: true,
  matcher: (token) => token.$type === 'color',
  transformer: (token) => {
    // For now, return the hex value
    // In a real implementation, you'd convert hex to OKLCH
    return token.value;
  },
});

// Custom transform for CSS custom property naming
StyleDictionary.registerTransform({
  name: 'name/css',
  type: 'name',
  transitive: true,
  transformer: (token) => {
    // Convert firm.core.color.blue.500 to --firm-core-color-blue-500
    return `--${token.path.join('-')}`;
  },
});

// Custom transform for TypeScript constant naming
StyleDictionary.registerTransform({
  name: 'name/ts',
  type: 'name',
  transitive: true,
  transformer: (token) => {
    // Convert firm.core.color.blue.500 to FIRM_CORE_COLOR_BLUE_500
    return token.path.join('_').toUpperCase();
  },
});

// Custom transform group for CSS variables
StyleDictionary.registerTransformGroup({
  name: 'css',
  transforms: [
    'attribute/cti',
    'name/css',
    'color/oklch',
    'size/px',
    'time/ms',
    'html/css',
  ],
});

// Custom transform group for TypeScript
StyleDictionary.registerTransformGroup({
  name: 'typescript',
  transforms: [
    'attribute/cti',
    'name/ts',
    'color/oklch',
    'size/px',
    'time/ms',
  ],
});

module.exports = {
  source: ['tokens.json'],
  platforms: {
    css: {
      transformGroup: 'css',
      buildPath: 'dist/',
      files: [
        {
          destination: 'variables.css',
          format: 'css/variables',
          options: {
            selector: ':root',
          },
        },
      ],
    },
    ts: {
      transformGroup: 'typescript',
      buildPath: 'dist/',
      files: [
        {
          destination: 'constants.ts',
          format: 'javascript/es6',
          options: {
            fileHeader: (defaultMessage) => [
              ...defaultMessage,
              '',
              'Generated design token constants',
              'DO NOT EDIT - Generated by Style Dictionary',
            ],
          },
        },
      ],
    },
    json: {
      transformGroup: 'css',
      buildPath: 'dist/',
      files: [
        {
          destination: 'tokens.json',
          format: 'json/nested',
        },
      ],
    },
  },
};
